CREATE DATABASE IF NOT EXISTS bancolegal
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
 
USE bancolegal;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `CONTA`;  
DROP TABLE IF EXISTS `OPERACAO`;  
DROP TABLE IF EXISTS `PESSOA`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CONTA (ID INT, NUMERO INT, AGENCIA INT, TITULAR INT, SENHA VARCHAR(30), SALDO DECIMAL, LIMITE DECIMAL, STATUS BOOLEAN, TIPO INT);
CREATE TABLE OPERACAO (ID INT, TIPO INT, VALOR INT, DATA DATE, ORIGEM VARCHAR(40), DESTINO VARCHAR(40));
CREATE TABLE PESSOA (ID INT, NOME VARCHAR(100), CPF VARCHAR(11), DATANASCIMENTO DATE, ENDERECO VARCHAR(100));